import z from "zod";

export const ActOnLeadSchema = z
    .object({
        ao_a: z.string().optional(),
        ao_f: z.string().optional(),
        ao_d: z.string().optional(),
        ao_p: z.string().optional(),
        ao_jstzo: z.string().optional(),
        ao_cuid: z.string().optional(),
        ao_srcid: z.string().optional(),
        ao_bot: z.string().optional(),
        ao_camp: z.string().optional(),
        "First Name": z.string(),
        "Last Name": z.string(),
        "E-mail Address": z.string().email(),
        "Home Phone": z.string().optional(),
        "Home Postal Code": z.string(),
        preferred_location: z.string(),
        dealername: z.string().optional(),
        dealermhwkacct: z.string().optional(),
        dealerurl: z.string().optional(),
        dealerfrom: z.string().optional(),
        dealerlogo: z.string().optional(),
        dealeraddr: z.string().optional(),
        dealeraddrline: z.string().optional(),
        dealerphone: z.string().optional(),
        dealerfacebook: z.string().optional(),
        dealertwitter: z.string().optional(),
        dealeryoutube: z.string().optional(),
        dealergooglep: z.string().optional(),
        dealerlinkedin: z.string().optional(),
        dealerinstagram: z.string().optional(),
        dealerpinterest: z.string().optional(),
        omnifycampaign: z.string().optional(),
        tags: z.string().optional().optional(),
        formname: z.string().optional(),
        promotion: z.string().optional(),
        source: z.string().optional(),
        foreignid: z.string().optional(),
        dealerzip: z.string().optional(),
        storelocation: z.string().optional(),
        formcategory: z.string().optional(),
        sourcedetail: z.string().optional(),
        sourceurl: z.string().optional(),
        dealercity: z.string().optional(),
        dealerstate: z.string().optional(),
        "traffic-type": z.string().optional(),
        "traffic-medium": z.string().optional(),
        "traffic-source": z.string().optional(),
        "traffic-term": z.string().optional(),
        "traffic-content": z.string().optional(),
        "traffic-campaign": z.string().optional(),
        "floorlytics-blob": z.string().optional(),
        notes: z.string().optional(),
        comments: z.string().optional(),
        optin: z.string().optional(),
        ao_form_neg_cap: z.string().optional(),
    })
    .passthrough();
export type ActOnLead = z.infer<typeof ActOnLeadSchema>;
