name: web2text
services:
  web2text:
    container_name: web2text-devcontainer
    build: 
      context: .
      dockerfile: DevContainer.dockerfile
    networks:
      - restate-network
    ports:
    # Restate service port
      - "9080:9080"
    volumes:
      - ./:/app
    restart: always
    command: "sleep infinity"
    environment:
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - RESTATE_ADMIN_URL=http://restate-server:9070
  restate-server:
    image: "docker.restate.dev/restatedev/restate:1.2.1"
    container_name: restate-server
    networks:
      - restate-network
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
    - "5122:5122" # NodeCtl - Control port for Restate Server nodes (gRPC + HTTP for Prometheus metrics /metrics)
    - "8080:8080" # Ingress - Acts as an API gateway for all services registered with Restate (HTTP)
    - "9070:9070" # Admin - Allows for CRUD operations on service/service deployment metadata, eg for service registration (HTTP)
    - "9071:9071" # Postgres - Exposes Restate RocksDB read-only storage operations using the Postgres protocol (Postgres)
    environment:
      RESTATE_TRACING_ENDPOINT: http://web2text-jaeger:4317
    restart: always
  dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: web2text-dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
   networks:
      - restate-network
  twilio_proxy:
    container_name: web2text-twilio-proxy
    env_file: "./.env"
    build: 
      context: "./modules/twilio_proxy"
    networks:
      - restate-network
    ports:
    # Proxy service port
      - "3000:3000"
    volumes:
      - ./modules/twilio_proxy/:/app
    restart: always
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - NUMBER_POOL=development
  web2text-jaeger:
    container_name: web2text-jaeger
    image: jaegertracing/all-in-one:1.46
    networks:
      - restate-network
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    restart: always
  web2text-swagger:
    container_name: web2text-swagger
    build:
      context: "./modules/swagger_docs"
    ports:
      - "8001:8080"
    volumes:
      - ./modules/swagger_docs/:/swagger_docs
    environment:
      SWAGGER_JSON: /swagger_docs/swagger.json
    networks:
      - restate-network
version: '3.9'
networks:
  restate-network: