name: lead-processor
services:
  dynamodb-local:
   image: "amazon/dynamodb-local:latest"
   container_name: lead-processor-dynamodb-local
   ports:
     - "8000:8000"
   restart: always
   networks:
      - restate-network
  # twilio_proxy:
  #   container_name: lead-processor-twilio-proxy
  #   env_file: "./.env.test"
  #   build: 
  #     context: "./modules/twilio_proxy"
  #   networks:
  #     - restate-network
  #   ports:
  #   # Proxy service port
  #     - "3000:3000"
  #   restart: always
  #   environment:
  #     - TWILIO_ACCOUNT_SID
  #     - TWILIO_AUTH_TOKEN
  #     - NUMBER_POOL=development
version: '3.9'
networks:
  restate-network: