name: web2text
services:
  web2text:
    container_name: web2text-devcontainer
    build: 
      context: ./
      dockerfile: Dockerfile
    networks:
      - restate-network
    ports:
    # Restate service port
      - "9075:9075"
    # NodeJS debug port
      - "9080:9080"
    volumes:
      - ./:/app
    restart: always
    command: "sleep infinity"
    environment:
     AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
     AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
  restate-server:
    image: "docker.io/restatedev/restate:latest"
    container_name: web2text-restate-server
    networks:
      - restate-network
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
    - "8080:8080"
    - "9070:9070"
    - "9071:9071"
  dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: web2text-dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
   networks:
      - restate-network
  twilio_proxy:
    container_name: web2text-twilio-proxy
    build: 
      context: ./twilio_proxy/
      dockerfile: Dockerfile
    networks:
      - restate-network
    ports:
    # Proxy service port
      - "3000:3000"
    volumes:
      - ./twilio_proxy/:/app
    restart: always
networks:
  restate-network: