name: web2text
services:
  web2text:
    container_name: web2text-devcontainer
    build: 
      context: .
    networks:
      - restate-network
    ports:
    # Restate service port
      - "9080:9080"
    restart: always
    command: "sleep infinity"
    environment:
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - CI
      - GITHUB_ACTIONS
  restate-server:
    image: "docker.io/restatedev/restate:1.1.6"
    container_name: web2text-restate-server
    networks:
      - restate-network
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
    - "5122:5122"
    - "5123:5123"
    - "8080:8080"
    - "9070:9070"
    - "9071:9071"
    restart: always
  dynamodb-local:
   image: "amazon/dynamodb-local:latest"
   container_name: web2text-dynamodb-local
   ports:
     - "8000:8000"
   restart: always
   networks:
      - restate-network
  twilio_proxy:
    container_name: web2text-twilio-proxy
    env_file: "./.env.test"
    build: 
      context: "./modules/twilio_proxy"
    networks:
      - restate-network
    ports:
    # Proxy service port
      - "3000:3000"
    restart: always
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - NUMBER_POOL=development
    container_name: web2text-jaeger
    image: jaegertracing/all-in-one:1.46
    networks:
      - restate-network
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    restart: always
version: '3.9'
networks:
  restate-network: