name: lead-processor
services:
  lead-processor:
    container_name: lead-processor-devcontainer
    build: 
      context: .
      dockerfile: DevContainer.dockerfile
    networks:
      - restate-network
    ports:
    # Restate service port
      - "9080:9080"
    restart: always
    command: "sleep infinity"
    environment:
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - CI
      - GITHUB_ACTIONS
  restate-server:
    image: "docker.restate.dev/restatedev/restate:1.3.2"
    container_name: restate-server
    networks:
      - restate-network
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
    - "5122:5122" # NodeCtl - Control port for Restate Server nodes (gRPC + HTTP for Prometheus metrics /metrics)
    - "8080:8080" # Ingress - Acts as an API gateway for all services registered with Restate (HTTP)
    - "9070:9070" # Admin - Allows for CRUD operations on service/service deployment metadata, eg for service registration (HTTP)
    - "9071:9071" # Postgres - Exposes Restate RocksDB read-only storage operations using the Postgres protocol (Postgres)
    restart: always
  dynamodb-local:
   image: "amazon/dynamodb-local:latest"
   container_name: lead-processor-dynamodb-local
   ports:
     - "8000:8000"
   restart: always
   networks:
      - restate-network
  # twilio_proxy:
  #   container_name: lead-processor-twilio-proxy
  #   env_file: "./.env.test"
  #   build: 
  #     context: "./modules/twilio_proxy"
  #   networks:
  #     - restate-network
  #   ports:
  #   # Proxy service port
  #     - "3000:3000"
  #   restart: always
  #   environment:
  #     - TWILIO_ACCOUNT_SID
  #     - TWILIO_AUTH_TOKEN
  #     - NUMBER_POOL=development
version: '3.9'
networks:
  restate-network: