#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

bun run biome check --write --staged --no-errors-on-unmatched

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add