name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the stack
        run: docker compose -f docker-compose.yaml up --build --force-recreate
      - name: Execute tests in the running services
        run: |
          docker-compose exec web2text-devcontainer bun run e2e
