name: Docker Compose Action

on: [push]
env: # Or as an environment variable
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Copy test env vars
        run: cp modules/e2e_tests/.env.test ./.env
      - name: Build the stack
        run: docker compose -f docker-compose.yaml up --build --force-recreate -d
      - name: Execute tests in the running services
        run: |
          docker compose exec -T web2text-devcontainer bun run e2e

      - name: Stop and remove containers
        run: docker compose down