name: Docker Compose Action

on: [push]
env: # Or as an environment variable
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  HUSKY: 0
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun run check
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Copy Test ENV vars
        run: cp .env.test .env
      - name: Start Services
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: ./docker-compose.test.yaml
          up-flags: --build --force-recreate
      - name: Wait for Services To Be Ready
        run: sleep 5
      - name: Run E2E Tests
        run: docker compose -f ./docker-compose.test.yaml exec lead-processor bun run e2e