name: Docker Compose Action

on: [push]
env: # Or as an environment variable
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  HUSKY: 0
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          no-cache: true
          bun-version: 1.2.10
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun run check
  e2e:
    runs-on: ubuntu-latest
    services:
      lead-processor-dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        environment:
          - AWS_ACCESS_KEY_ID=test
          - AWS_SECRET_ACCESS_KEY=test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          no-cache: true
          bun-version: 1.2.10
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Add Dynamodb local to /etc/hosts
        run: |
          echo "127.0.0.1 lead-processor-dynamodb-local" | sudo tee -a /etc/hosts
      - name: Run E2E Tests
        run: bun run e2e